#!/bin/bash
#SBATCH --job-name=dep_stage1
#SBATCH --partition=debug
#SBATCH --cpus-per-task=1
#SBATCH --mem=256M
#SBATCH --time=00:01:00
#SBATCH --output=/tmp/dep_stage1_%j.out
#SBATCH --error=/tmp/dep_stage1_%j.err

echo "=== FLURM Test Job: Dependency Stage 1 (Data Generation) ==="
echo "Job ID: $SLURM_JOB_ID"
echo "Hostname: $(hostname)"
echo "Start time: $(date)"

# Generate some data for downstream stages
DATA_FILE="/tmp/pipeline_data_${SLURM_JOB_ID}.txt"
echo "Generating data to $DATA_FILE..."

# Create data file
cat > "$DATA_FILE" << EOF
# Pipeline data generated by job $SLURM_JOB_ID
timestamp=$(date +%s)
job_id=$SLURM_JOB_ID
hostname=$(hostname)
random_value=$RANDOM
data_items=100
EOF

# Generate some data items
for i in $(seq 1 100); do
    echo "item_$i=$RANDOM" >> "$DATA_FILE"
done

echo "Generated $(wc -l < "$DATA_FILE") lines of data"

echo "End time: $(date)"
echo "SUCCESS - Stage 1 complete"
echo "Data file: $DATA_FILE"
